### ISSUE TITLE
Convert Currency isn't working anymore?

### ISSUE THREAD

**Issue by MartinAyla** [hlissner/lb6-actions#10]
I'm using the latest version of LB and the extension.

"There was an error with the request..."

**Comment by hlissner** [comment]
I'm aware of this. I'll look into it later today and let you know.

**Comment by hlissner** [comment]
Alright, this has been fixed. The old API I was using shut down, so I moved over to [currencylayer.com](https://currencylayer.com). The bad news: you need an API key. The good news: it's free!

When you first run the action, the error message will have a button labeled "Preferences" that will open your preferences so you can enter your api key.

Let me know if you have any trouble.

**Comment by MartinAyla** [comment]
Thanks, works great!

**Comment by megadr01d** [comment]
:+1:
