### ISSUE TITLE
Enter Path in Dialog not working

### ISSUE THREAD

**Issue by sinewave** [hlissner/lb6-actions#11]
Hey,

Installed this action but i can't get it to work. It seems to trigger the Cmd-Shift-G shortcut and the enter path textfield appears but the actual file/folder path isnt entered and it just remains there.

Tony

**Comment by hlissner** [comment]
That should do it. Give it a try and let me know.

**Comment by sinewave** [comment]
Works great. thx!!

**Comment by megadr01d** [comment]
No discredit to this action as I used it extensively but LB provides built-in functionality for this in case someone is not aware of it. In a save dialog, invoke LB, navigate to your desired folder, hit <kbd>Shift + Command + C</kbd> (Copy and Paste Folder) and hit <kbd>Enter</kbd>.

Sorry if this is mentioned somewhere but just thought I could share it.
In any case, thanks hlissner for your most useful actions as I use more than half a dozen of them (just updated Convert Currency, thanks for that).

**Comment by hlissner** [comment]
> Apparently the above only works in Cocoa apps

@megadr01d Yeah, this action is a bit hackish. It literally presses command+shift+G and pastes in the path manually. Maybe the delay between the two should be longer? This was the initial problem with the script.

Thanks for the tip though, that's a great alternative!

>In any case, thanks hlissner

And you're very welcome!
