### ISSUE TITLE
Shorten URL (yourls) config

### ISSUE THREAD

**Issue by benbeton** [hlissner/lb6-actions#12]
Hi,

could anyone please tell a bit more detailed, how to do the config, I don't understand the short manual given.

thank you

**Comment by hlissner** [comment]
Oh, those instructions _are_ too minimalistic. I must've been in a hurry putting that up! I'll fix that. 

In the meantime:

1. Install Shorten URL (YourLS).lbaction by:
* [Downloading the entire repo as a zip file](https://github.com/hlissner/lb6-actions/archive/master.zip)
* Unzipping the zip file
* Double clicking Shorten URL (YourLS).lbaction (note: this action only works for LaunchBar 6+)

2. Log on to your YourLS website. For instance, mine is at http://v0.io -- you can get to the admin panel at https://v0.io/admin

3. Go to the **tools** page (e.g. http://v0.io/admin/tools)

4. Scroll down to "Secure passwordless API call" and take note of your **security token** and **URL to yourls-api.php**.

5. Run the Shorten URL (YourLS) action with <kbd>Control</kbd> held down (you might have to type in something before it runs—sorry, this is a little clumsy. I'll fix this too!). This will cause it to return the Preferences.plist file for the action.

6. Open said file, and you should see this window:

![](http://i.cubeupload.com/gDs78K.png)

7. I've put "ABC" and "123" in for signature and url. Replace those with the security token and yourls-api.php url, respectively.

And you should be good to go! Let me know if you have trouble.

**Comment by benbeton** [comment]
Hi, wow thats a lot more detailed. The only part that is not working for me is step 5, configuring the preferences.plist. 
The Folder you mentioned is empty :( maybe that's why I had trouble to get the file through "hold down control"

thank you for your work and help!

**Comment by hlissner** [comment]
Oh! I just noticed that the action doesn't _create_ the Preferences.plist until you run it once. Whoops! Another thing to fix.

Try running the action as normal (with the expectation it will fail). After the first failure, try the <kbd>control</kbd> trick again and the file should exist.

**Comment by benbeton** [comment]
thank you @hlissner, now it is working perfectly!

**Comment by hlissner** [comment]
You're very welcome. Also, I just pushed all the above-mentioned fixes.

**Comment by paradeiser** [comment]
I know it's an old thread, but the only thing I could find about a LaunchBar Action for yourls.

I also get an error message when trying to run the action, but mine states:
`Error: Error loading script: Die Datei „notify.js“ konnte nicht geöffnet werden, da sie nicht existiert. /Users/…/Library/Application Support/LaunchBar/Actions/Shorten URL (YourLS).lbaction/Contents/Scripts/shared/lib/notify.js (line 1).`

Also the "shared" folder in the zip file is empty. Do I have to get / copy "notify.js", "request.js" and "url.js" somewhere manually?

Would be great to get this working ;)
Thanks a lot!
paradeiser

**Comment by sentience** [comment]
@paradeiser See #39 for the extra steps you need to complete if you are installing from a Git clone of this project.

**Comment by paradeiser** [comment]
Thanks for your reply! But could you please elaborate a little more?
Sorry, I don't understand.

**Comment by sentience** [comment]
Normally you are supposed to install the actions using the download links in the README, not by using a clone of this repository on your computer.

But because the download links are currently broken, we _must_ use a clone of this repository.

The error you're getting is because after making the clone of the repository, the actions are not yet ready to be installed. You must first run the additional setup steps: `git submodule init`, `git submodule update`, and then `rake`. Once you've run those 4 commands, you can then install any of the actions, and they will work.

(All of this assumes you are cloning the repository, not just downloading a copy of its files. You will need Git installed on your computer to do that, and you will need the Ruby programming language and the Rake gem for it installed so you can run the `rake` command.)

**Comment by paradeiser** [comment]
Great - thanks! I got it working.

(Also had to repair dev tools first on macOS "xcode-select --install" as I hardly use them)
