### ISSUE TITLE
Hourly forecast in Forecast Action

### ISSUE THREAD

**Issue by lordlycastle** [hlissner/lb6-actions#16]
It would be nice to include hourly forecast for Today item in the Forecast action. 

Perhaps _Today_ item could be an action, which, when run would fetch the forecast for next few hours?
Or when Forecast action is run, it could return _Today_ with children array, which contains the hourly forecast; this way you would be able to navigate up-and-down.

**Comment by hlissner** [comment]
Sorry for the late response: I've decided to remove Forecast.lbaction. Instead, I recommend prenagha's [excellent Forecast action](http://prenagha.github.io/launchbar/forecast.html) as a replacement. I haven't tried it myself but it seems to have many more features.
