### ISSUE TITLE
Temperature In: API no longer working?

### ISSUE THREAD

**Issue by hlissner** [hlissner/lb6-actions#19]

**Comment by megadr01d** [comment]
Confirmed.

**Comment by hlissner** [comment]
Alright, that should do it.

It seems that the api provider doesn't allow API key-less requests anymore. I've included a default API key with the action. If you hit rate-limit errors you'll have to sign up for your own at http://openweathermap.org (it's free).

Let me know if any problems persist.

**Comment by megadr01d** [comment]
:+1: Fixed, thanks.
