### ISSUE TITLE
Convert Currency just does't work

### ISSUE THREAD

**Issue by geekjony** [hlissner/lb6-actions#22]
I have know idea if I made some mistake.

I have added my api-key into the preference.plist, but when I use the action, it shows a warning.
<img width="564" alt="screen shot 2015-12-23 at 10 57 48" src="https://cloud.githubusercontent.com/assets/14588641/11970362/847863dc-a964-11e5-8cd8-716786483a66.png">

How to fix this?

thx :)

**Comment by hlissner** [comment]
Odd. Could you include steps to reproduce the error? Also, what version of the action are you running, and what input are you giving it?

**Comment by geekjony** [comment]
Sorry to response so late.

Acutually I just followed the installation guide.

The Action’s version is 2.2.3.

I’m not sure if the API I input is wrong, it’s a string with32 letters and
numbers I got after I sign up the site you mentioned.

[image: Screen Shot 2016-01-05 at 11.08.46.png]

Henrik Lissner <notifications@github.com>于2015年12月23日周三 下午12:31写道：

**Comment by hlissner** [comment]
I've been looking into this and haven't been able to reproduce the issue. Could you send me your Preferences.plist file?

**Comment by geekjony** [comment]
This is

Henrik Lissner <notifications@github.com>于2016年1月9日周六 上午10:22写道：

**Comment by hlissner** [comment]
I did not receive anything. Could you send it to henrik@lissner.net?

**Comment by hlissner** [comment]
The Preferences file seems to be fine so it must be your input. Could you show me what text input you're entering into the action, exactly?

**Comment by geekjony** [comment]
So sorry… The format I input is a little wrong.
The problem has been solved.
Thank you very much.

Henrik Lissner <notifications@github.com>于2016年1月11日周一 上午11:19写道：

**Comment by hlissner** [comment]
I'm glad you resolved it! However, could you share what input you were entering? So I can make the error message more helpful.

**Comment by geekjony** [comment]
[image: Screen Shot 2016-01-11 at 13.54.47.png]Of course.
Actually - -, I just used CHY by mistake instead of CNY.

Henrik Lissner <notifications@github.com>于2016年1月11日周一 下午4:35写道：

**Comment by hlissner** [comment]
Thanks! I'll incorporate a more helpful error message soon.
