### ISSUE TITLE
Send to Imgur - malformed response

### ISSUE THREAD

**Issue by Pe8er** [hlissner/lb6-actions#25]
Alert says "An error occurred while running “Send to Imgur”, "TypeError: undefined is not an object (evaluating 'results.map') (line 29)."

**Comment by hlissner** [comment]
Thanks for reporting! I'll look into it over the weekend.

**Comment by hlissner** [comment]
Looks like version 2 of Imgur's API was finally shut down — I'd have to do a rewrite for v3 and OAuth2 support. Unfortunately, I don't have time to do it now so it'll have to wait.

**Comment by kerhbal** [comment]
solved by https://github.com/hlissner/lb6-actions/pull/38
