### ISSUE TITLE
launch path not accesible in Image optimize action

### ISSUE THREAD

**Issue by jimmyhartington** [hlissner/lb6-actions#26]
When running the optimize action I get the attached error. 
I have both ImageAlpha.app and ImageOptim.app installed in Applications.
![skaermbillede 2016-10-19 kl 09 28 21](https://cloud.githubusercontent.com/assets/2161490/19509297/695ae392-95de-11e6-8a3f-2238a213a460.png)
![skaermbillede 2016-10-19 kl 09 26 34](https://cloud.githubusercontent.com/assets/2161490/19509298/69802e04-95de-11e6-8bf6-2a56790e394e.png)

**Comment by hlissner** [comment]
Good catch. I've been using an updated copy that fixes this, but I haven't pushed it yet. I'll do some more testing and resolve this sometime during the week.

**Comment by johnnycash69** [comment]
Well it's a long week ;)

Could you release the updated version please?

**Comment by hlissner** [comment]
Holy crap. I completely forgot about this issue! I don't use launchbar anymore and I'm not sure if you're still dealing with, but [I've uploaded an updated version now](https://v0.io/dl/launchbar/Optimize Image.lbaction.zip).

**Comment by jimmyhartington** [comment]
Thanks. 
It works fine on a jpeg. 
But I get the attached error, when running it on a png.
![skaermbillede 2017-08-31 kl 15 39 04](https://user-images.githubusercontent.com/2161490/29926075-a36f801a-8e62-11e7-9aab-4608063fcdff.png)
