### ISSUE TITLE
Cannot get convert currency to work

### ISSUE THREAD

**Issue by jannejava** [hlissner/lb6-actions#30]
Got this error Error: Error loading script:  ”notify.js.”
Convert Currency.lbaction/Contents/Scripts/shared/lib/notify.js

If I read the commit history, I can see that shared/lib/notify.js was deleted last year. Also is see that api.js and default.js are including files from shared/lib, which all seems to be deleted.

Thanks in advance!

**Comment by hlissner** [comment]
I'm guessing you downloaded the repo and tried to install the lbaction straight. There are extra steps to follow to 'build' the action before that will work.

Instead, download the action through [the download link in the README](https://v0.io/dl/launchbar/Convert%20Currency.lbaction.zip), this is pre-built and up to date, and won't have this problem.

**Comment by jannejava** [comment]
Ah, now it working! I got confused. Found some other repos with actions for ActionBar where you just installed with out build. Thanks for your answer and sorry for this.
