### ISSUE TITLE
Download.zip Does Not Appear on Page for Specific Action

### ISSUE THREAD

**Issue by JMichaelTX** [hlissner/lb6-actions#36]
Thanks for developing and sharing your LB Actions.

On the page for the [Chrome Tabs action](https://github.com/hlissner/lb6-actions/tree/master/Chrome%20Tabs.lbaction), the ReadMe states:

> Click "Download ZIP" on the right

This cannot be found.
As far as I can tell, we have to go to the [main page for ALL of your LB Actions](https://github.com/hlissner/lb6-actions), then click on the "Download" button which downloads ALL Actions in one zip.

It would be very nice if you could provide a separate download zip for each LB Action.

**Comment by hlissner** [comment]
You'll find download links [on this project's README](https://github.com/hlissner/lb6-actions#actions) for each action:

![image](https://user-images.githubusercontent.com/510883/53705855-5f7fbe80-3df5-11e9-865b-c0382d523728.png)

I'll look into updating the readme soon.
