### ISSUE TITLE
Error Message Launching Currency Converter

### ISSUE THREAD

**Issue by parkernathan** [hlissner/lb6-actions#37]
![2019-07-04_22-14-21](https://user-images.githubusercontent.com/52555509/60696206-59384680-9eaa-11e9-8c68-c06ac4a69d06.png)
When I launch Currency Converter after installing it, I receive the error message attached. I found the file I needed to add my API key. I added my API key to the sections of the file and restarted LaunchBar. Still receive the error message.

**Comment by hlissner** [comment]
As mentioned in #24, #28, #30, #33 and the README:

> _**Do not download this repo**_ to install these actions. If you do anyway, you need to run `rake` before any of the lbaction files are ready for installation.

Normally, you need to download the action through the download links listed on the README. You'll find convert currency's here: https://dl.v0.io/lb6/Convert%20Currency.lbaction.zip. However, I turned off the server while I'm traveling so it is currently unavailable.

Hope that helps!

**Comment by zhuxiaoxi** [comment]
https://github.com/hlissner/lb6-actions/issues/34#issuecomment-425367435
