### ISSUE TITLE
Shorten URL (Bit.ly) error

### ISSUE THREAD

**Issue by tomgenoni** [hlissner/lb6-actions#4]
I'm getting an error when trying to use the bit.ly URL shortener action. 

![screen shot 2015-01-19 at 10 30 18 pm](https://cloud.githubusercontent.com/assets/1171072/5813021/daba909c-a02a-11e4-873f-e036ab4c1413.png)

**Comment by hlissner** [comment]
Whoops! Some left over code was lying around. Consider it...

**Comment by hlissner** [comment]
...fixed!

**Comment by tomgenoni** [comment]
Faster next time! I was just about to root around and see if I could fix it. Thanks for the quick response and your work on these. Very useful.

**Comment by hlissner** [comment]
Haha, no problem!
