### ISSUE TITLE
Bitly URL shortener not added to clipboard

### ISSUE THREAD

**Issue by tgenoni** [hlissner/lb6-actions#5]
Not sure if I'm missing a step but after adding my access token to the bit.ly shortener action I'm able to receive the shortened URL but don't seem to be able to access it. 
![screen shot 2015-01-20 at 1 53 00 pm](https://cloud.githubusercontent.com/assets/7852572/5827014/1a49a852-a0ac-11e4-9efa-fddf92a25485.png)

Hit return:

![screen shot 2015-01-20 at 1 53 48 pm](https://cloud.githubusercontent.com/assets/7852572/5827019/201281be-a0ac-11e4-9dd9-af41ac2f96ec.png)

At this point nothing has been added to my clipboard. If I command-C the result:

![screen shot 2015-01-20 at 1 55 56 pm](https://cloud.githubusercontent.com/assets/7852572/5827027/2ee3197e-a0ac-11e4-87dd-4d172f2c54a6.png)

But what's on my clipboard is 'http://foo.com' and not the shortened URL.

**Comment by hlissner** [comment]
Good catch. In an earlier version of LB, it would copy the title, not the destination url. That's fixed. I'll implement pushing the result to the clipboard automatically in a moment.

**Comment by tgenoni** [comment]
Thanks, confirmed that command-C is working.

**Comment by hlissner** [comment]
And done! The short url is now auto-copied to clipboard.
