### ISSUE TITLE
Send to Imgur

### ISSUE THREAD

**Issue by aristidesfl** [hlissner/lb6-actions#7]
I made a script to upload pics to imgur a long time ago.
https://github.com/aristidesfl/launchbar-scripts

Still applescript but it works reliably, I use it every day. 
If you don't provide a file it initiates a screen capture.

**Comment by hlissner** [comment]
Excellent! Would you mind if I wrapped it (and your send-to-dropbox action) up in an lbaction?

Only tweak I forsee are prompts for the imgur API key and dropbox user ID.

**Comment by aristidesfl** [comment]
Sure. Additionally a pull request with the modifications would also be very welcome.

**Comment by aristidesfl** [comment]
Just made a few small changes to the scripts https://github.com/aristidesfl/launchbar-scripts/commits/master

**Comment by hlissner** [comment]
I ended up porting it to JS, but it's done! Thanks for the help!
